RAN AND BUILT with NAVIGATION ERRORS
1. The navigation to contacts works. I just need to implement the contact list there, the add/delete/edit functionality, and a blank profile page.

2.
**ERROR**: When clicking the link to the profile page, I got
```
java.lang.IllegalArgumentException: Navigation destination that matches route PROFILE cannot be found in the navigation graph ComposeNavGraph(0x0) startDestination={Destination(0x78c93dec) route=HOME}
```
which is like of course because I have not implemented a profile page yet.

---

**TODO**:
  1. Add Contacts page functionality (add, edit, delete)
  2. add a filter option for items
  3. add a basic profile page
  4. Make the ui more vibrant and make the list rows use cards for a modern look